### ISSUE TITLE
Pmenu needs background

### ISSUE THREAD

**Issue by gangelop** [marcopaganini/termschool-vim-theme#5]
Pmenu needs a background color to clearly differentiate it from the general background.

Example:
![2016-11-08-074030_765x457_scrot](https://cloud.githubusercontent.com/assets/1893345/20089355/b3e78e12-a586-11e6-8ae9-43f8365cb789.png)

**Comment by gangelop** [comment]
How about:

```
hi Pmenu ctermfg=NONE ctermbg=59 cterm=NONE guifg=NONE guibg=#5f5f5f gui=NONE
hi PmenuSel ctermfg=NONE ctermbg=23 cterm=NONE guifg=NONE guibg=#005f5f gui=NONE
```

![2016-11-08-075230_702x418_scrot](https://cloud.githubusercontent.com/assets/1893345/20089612/6b0f67d0-a588-11e6-80c2-7071dd7b5dc2.png)

**Comment by marcopaganini** [comment]
Done! Thanks for the idea.

**Comment by gangelop** [comment]
cool. ty!
